package com.github.lunatrius.profiles;

import net.minecraft.client.Minecraft;
import net.minecraft.client.settings.GameSettings;

public class Profile {
	private boolean invertMouse;
	private float mouseSensitivity;
	private float fov;
	private float gamma;
	private int renderDistance;
	private int guiScale;
	private int particles;
	private boolean viewBobbing;
	private boolean anaglyph;
	private boolean advancedOpengl;
	private int maxFps;
	private int difficulty;
	private boolean fancyGraphics;
	private int ambientOcclusion;
	private boolean clouds;
	private String language;
	private int chatVisibility;
	private boolean chatColors;
	private boolean chatLinks;
	private boolean chatLinksPrompt;
	private float chatOpacity;
	private boolean serverTextures;
	private boolean snooper;
	private boolean fullscreen;
	private boolean vsync;
	private boolean advancedItemTooltips;
	private boolean pauseOnLostFocus;
	private boolean showCape;
	private boolean touchscreen;
	private int overrideWidth;
	private int overrideHeight;
	private boolean heldItemTooltips;
	private float chatHeightFocused;
	private float chatHeightUnfocused;
	private float chatScale;
	private float chatWidth;
	private float music;
	private float sound;

	public static Profile fromGameSettings(GameSettings gameSettings) {
		Profile profile = new Profile();
		profile.invertMouse = gameSettings.invertMouse;
		profile.invertMouse = gameSettings.invertMouse;
		profile.mouseSensitivity = gameSettings.mouseSensitivity;
		profile.fov = gameSettings.fovSetting;
		profile.gamma = gameSettings.gammaSetting;
		profile.renderDistance = gameSettings.renderDistance;
		profile.guiScale = gameSettings.guiScale;
		profile.particles = gameSettings.particleSetting;
		profile.viewBobbing = gameSettings.viewBobbing;
		profile.anaglyph = gameSettings.anaglyph;
		profile.advancedOpengl = gameSettings.advancedOpengl;
		profile.maxFps = gameSettings.limitFramerate;
		profile.difficulty = gameSettings.difficulty;
		profile.fancyGraphics = gameSettings.fancyGraphics;
		profile.ambientOcclusion = gameSettings.ambientOcclusion;
		profile.clouds = gameSettings.clouds;
		profile.language = gameSettings.language;
		profile.chatVisibility = gameSettings.chatVisibility;
		profile.chatColors = gameSettings.chatColours;
		profile.chatLinks = gameSettings.chatLinks;
		profile.chatLinksPrompt = gameSettings.chatLinksPrompt;
		profile.chatOpacity = gameSettings.chatOpacity;
		profile.serverTextures = gameSettings.serverTextures;
		profile.snooper = gameSettings.snooperEnabled;
		profile.fullscreen = gameSettings.fullScreen;
		profile.vsync = gameSettings.enableVsync;
		profile.advancedItemTooltips = gameSettings.advancedItemTooltips;
		profile.pauseOnLostFocus = gameSettings.pauseOnLostFocus;
		profile.showCape = gameSettings.showCape;
		profile.touchscreen = gameSettings.touchscreen;
		profile.overrideWidth = gameSettings.overrideWidth;
		profile.overrideHeight = gameSettings.overrideHeight;
		profile.heldItemTooltips = gameSettings.heldItemTooltips;
		profile.chatHeightFocused = gameSettings.chatHeightFocused;
		profile.chatHeightUnfocused = gameSettings.chatHeightUnfocused;
		profile.chatScale = gameSettings.chatScale;
		profile.chatWidth = gameSettings.chatWidth;
		profile.music = gameSettings.musicVolume;
		profile.sound = gameSettings.soundVolume;
		return profile;
	}

	public static GameSettings toGameSettings(Profile profile) {
		GameSettings gameSettings = Minecraft.getMinecraft().gameSettings;
		gameSettings.invertMouse = profile.invertMouse;
		gameSettings.invertMouse = profile.invertMouse;
		gameSettings.mouseSensitivity = profile.mouseSensitivity;
		gameSettings.fovSetting = profile.fov;
		gameSettings.gammaSetting = profile.gamma;
		gameSettings.renderDistance = profile.renderDistance;
		gameSettings.guiScale = profile.guiScale;
		gameSettings.particleSetting = profile.particles;
		gameSettings.viewBobbing = profile.viewBobbing;
		gameSettings.anaglyph = profile.anaglyph;
		gameSettings.advancedOpengl = profile.advancedOpengl;
		gameSettings.limitFramerate = profile.maxFps;
		gameSettings.difficulty = profile.difficulty;
		gameSettings.fancyGraphics = profile.fancyGraphics;
		gameSettings.ambientOcclusion = profile.ambientOcclusion;
		gameSettings.clouds = profile.clouds;
		gameSettings.language = profile.language;
		gameSettings.chatVisibility = profile.chatVisibility;
		gameSettings.chatColours = profile.chatColors;
		gameSettings.chatLinks = profile.chatLinks;
		gameSettings.chatLinksPrompt = profile.chatLinksPrompt;
		gameSettings.chatOpacity = profile.chatOpacity;
		gameSettings.serverTextures = profile.serverTextures;
		gameSettings.snooperEnabled = profile.snooper;
		gameSettings.fullScreen = profile.fullscreen;
		gameSettings.enableVsync = profile.vsync;
		gameSettings.advancedItemTooltips = profile.advancedItemTooltips;
		gameSettings.pauseOnLostFocus = profile.pauseOnLostFocus;
		gameSettings.showCape = profile.showCape;
		gameSettings.touchscreen = profile.touchscreen;
		gameSettings.overrideWidth = profile.overrideWidth;
		gameSettings.overrideHeight = profile.overrideHeight;
		gameSettings.heldItemTooltips = profile.heldItemTooltips;
		gameSettings.chatHeightFocused = profile.chatHeightFocused;
		gameSettings.chatHeightUnfocused = profile.chatHeightUnfocused;
		gameSettings.chatScale = profile.chatScale;
		gameSettings.chatWidth = profile.chatWidth;
		gameSettings.musicVolume = profile.music;
		gameSettings.soundVolume = profile.sound;
		return gameSettings;
	}
}
